package com.atm.entities;

import java.util.UUID;

public class QRRequest {

	private double amount;
    private int atmId;
    private String tranId;
    private int customerId;
//    private int cardPin;

    // Default constructor
//    public QRRequest() {
//        this.tranId = generateTranId();  // Autogenerate tranId
//    }

//    public int getCardPin() {
//		return cardPin;
//	}
//
//	public void setCardPin(int cardPin) {
//		this.cardPin = cardPin;
//	}

	// Parameterized constructor
    public QRRequest(double amount, int atmId, int customerId,String tranId) {
        this.amount = amount;
        this.atmId = atmId;
        this.customerId = customerId;
        this.tranId = tranId;  // Autogenerate tranId
//        this.cardPin = cardPin;
    }

    public QRRequest() {}
    // Method to generate a transaction ID
//    private String generateTranId() {
//        return UUID.randomUUID().toString().substring(0, 8); // Short UUID
//    }

    // Getters and Setters
    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public int getAtmId() {
        return atmId;
    }

    public void setAtmId(int atmId) {
        this.atmId = atmId;
    }

    public String getTranId() {
        return tranId;
    }

    public void setTranId(String tranId) {
        this.tranId = tranId;  // Optionally allow setting, but it will be autogenerated by default
    }

    public int getCustomerId() {
        return customerId;
    }

    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    @Override
    public String toString() {
        return "QRRequest{" +
                "amount=" + amount +
                ", atmId=" + atmId +
                ", tranId='" + tranId + '\'' +
                ", customerId=" + customerId +
                '}';
    }
}